sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
      - python2.6
      - python3.5
env:
  global:
    # 77 modules.  Let's whittle this down!
    - PY3_EXCLUDE_LIST="cloud/amazon/cloudformation.py
      cloud/amazon/ec2_ami.py
      cloud/amazon/ec2_asg.py
      cloud/amazon/ec2_eip.py
      cloud/amazon/ec2_elb_lb.py
      cloud/amazon/ec2_elb.py
      cloud/amazon/ec2_group.py
      cloud/amazon/ec2_key.py
      cloud/amazon/ec2_lc.py
      cloud/amazon/ec2_metric_alarm.py
      cloud/amazon/ec2.py
      cloud/amazon/ec2_scaling_policy.py
      cloud/amazon/ec2_snapshot.py
      cloud/amazon/ec2_vol.py
      cloud/amazon/ec2_vpc_net.py
      cloud/amazon/ec2_vpc.py
      cloud/amazon/elasticache.py
      cloud/amazon/elasticache_subnet_group.py
      cloud/amazon/iam_cert.py
      cloud/amazon/iam_policy.py
      cloud/amazon/iam.py
      cloud/amazon/rds_param_group.py
      cloud/amazon/rds.py
      cloud/amazon/rds_subnet_group.py
      cloud/amazon/route53.py
      cloud/amazon/s3.py
      cloud/digital_ocean/digital_ocean_domain.py
      cloud/digital_ocean/digital_ocean.py
      cloud/digital_ocean/digital_ocean_sshkey.py
      cloud/docker/docker_container.py
      cloud/docker/docker_image_facts.py
      cloud/docker/docker_login.py
      cloud/google/gce_lb.py
      cloud/google/gce_net.py
      cloud/google/gce_pd.py
      cloud/google/gce.py
      cloud/google/gc_storage.py
      cloud/openstack/_glance_image.py
      cloud/openstack/_keystone_user.py
      cloud/openstack/_nova_compute.py
      cloud/openstack/_nova_keypair.py
      cloud/openstack/_quantum_floating_ip_associate.py
      cloud/openstack/_quantum_floating_ip.py
      cloud/openstack/_quantum_network.py
      cloud/openstack/_quantum_router_gateway.py
      cloud/openstack/_quantum_router_interface.py
      cloud/openstack/_quantum_router.py
      cloud/openstack/_quantum_subnet.py
      cloud/rackspace/rax_cbs_attachments.py
      cloud/rackspace/rax_cbs.py
      cloud/rackspace/rax_cdb_database.py
      cloud/rackspace/rax_cdb.py
      cloud/rackspace/rax_cdb_user.py
      cloud/rackspace/rax_clb_nodes.py
      cloud/rackspace/rax_clb.py
      cloud/rackspace/rax_dns.py
      cloud/rackspace/rax_dns_record.py
      cloud/rackspace/rax_facts.py
      cloud/rackspace/rax_files_objects.py
      cloud/rackspace/rax_files.py
      cloud/rackspace/rax_keypair.py
      cloud/rackspace/rax_meta.py
      cloud/rackspace/rax_network.py
      cloud/rackspace/rax.py
      cloud/rackspace/rax_queue.py
      cloud/rackspace/rax_scaling_group.py
      cloud/rackspace/rax_scaling_policy.py
      cloud/vmware/vsphere_guest.py
      utilities/helper/accelerate.py
      utilities/logic/async_status.py
      utilities/logic/async_wrapper.py
      utilities/logic/wait_for.py"
before_install:
  - git config user.name "ansible"
  - git config user.email "ansible@ansible.com"
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then git rebase $TRAVIS_BRANCH; fi;
install:
  - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
  - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
script:
  - python2.4 -m compileall -fq -x 'cloud/' .
  - python2.4 -m compileall -fq cloud/amazon/_ec2_ami_search.py cloud/amazon/ec2_facts.py
  - python2.6 -m compileall -fq .
  - python2.7 -m compileall -fq .
  - python3.4 -m compileall -fq . -x $(echo "$PY3_EXCLUDE_LIST"| tr ' ' '|')
  - python3.5 -m compileall -fq . -x $(echo "$PY3_EXCLUDE_LIST"| tr ' ' '|')
  - ansible-validate-modules --exclude 'utilities/' .
    #- ansible-validate-modules --exclude 'cloud/amazon/ec2_lc\.py|cloud/amazon/ec2_scaling_policy\.py|cloud/amazon/ec2_scaling_policy\.py|cloud/amazon/ec2_asg\.py|cloud/azure/azure\.py|packaging/os/rhn_register\.py|network/openswitch/ops_template\.py|system/hostname\.py|utilities/' .
  #- ./test-docs.sh core
