sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
      - python2.6
      - python3.5
env:
  global:
    - PY3_EXCLUDE_LIST="cloud/amazon/cloudtrail.py
      cloud/amazon/dynamodb_table.py
      cloud/amazon/ec2_ami_copy.py
      cloud/amazon/ec2_customer_gateway.py
      cloud/amazon/ec2_elb_facts.py
      cloud/amazon/ec2_eni_facts.py
      cloud/amazon/ec2_eni.py
      cloud/amazon/ec2_remote_facts.py
      cloud/amazon/ec2_snapshot_facts.py
      cloud/amazon/ec2_vol_facts.py
      cloud/amazon/ec2_vpc_igw.py
      cloud/amazon/ec2_vpc_nacl.py
      cloud/amazon/ec2_vpc_net_facts.py
      cloud/amazon/ec2_vpc_route_table_facts.py
      cloud/amazon/ec2_vpc_route_table.py
      cloud/amazon/ec2_vpc_subnet_facts.py
      cloud/amazon/ec2_vpc_subnet.py
      cloud/amazon/ecs_cluster.py
      cloud/amazon/ecs_service_facts.py
      cloud/amazon/ecs_service.py
      cloud/amazon/ecs_taskdefinition.py
      cloud/amazon/ecs_task.py
      cloud/amazon/route53_facts.py
      cloud/amazon/route53_health_check.py
      cloud/amazon/route53_zone.py
      cloud/amazon/s3_bucket.py
      cloud/amazon/s3_lifecycle.py
      cloud/amazon/s3_logging.py
      cloud/amazon/sns_topic.py
      cloud/amazon/sqs_queue.py
      cloud/amazon/sts_assume_role.py
      cloud/amazon/sts_session_token.py
      cloud/centurylink/clc_aa_policy.py
      cloud/centurylink/clc_group.py
      cloud/centurylink/clc_publicip.py
      cloud/google/gce_img.py
      cloud/google/gce_tag.py
      cloud/misc/ovirt.py
      cloud/misc/proxmox.py
      cloud/misc/proxmox_template.py
      cloud/misc/virt_net.py
      cloud/misc/virt_pool.py
      cloud/misc/virt.py
      cloud/profitbricks/profitbricks.py
      cloud/profitbricks/profitbricks_volume.py
      cloud/rackspace/rax_clb_ssl.py
      cloud/xenserver_facts.py
      clustering/consul_acl.py
      clustering/consul_kv.py
      clustering/consul.py
      clustering/consul_session.py
      commands/expect.py
      database/misc/mongodb_parameter.py
      database/misc/mongodb_user.py
      database/misc/redis.py
      database/mysql/mysql_replication.py
      database/postgresql/postgresql_ext.py
      database/postgresql/postgresql_lang.py
      database/vertica/vertica_configuration.py
      database/vertica/vertica_facts.py
      database/vertica/vertica_role.py
      database/vertica/vertica_schema.py
      database/vertica/vertica_user.py
      monitoring/bigpanda.py
      monitoring/boundary_meter.py
      monitoring/circonus_annotation.py
      monitoring/datadog_monitor.py
      monitoring/rollbar_deployment.py
      monitoring/sensu_check.py
      monitoring/stackdriver.py
      monitoring/zabbix_group.py
      monitoring/zabbix_hostmacro.py
      monitoring/zabbix_host.py
      monitoring/zabbix_screen.py
      network/citrix/netscaler.py
      network/cloudflare_dns.py
      network/dnsimple.py
      network/dnsmadeeasy.py
      network/f5/bigip_facts.py
      network/f5/bigip_gtm_virtual_server.py
      network/f5/bigip_gtm_wide_ip.py
      network/f5/bigip_monitor_http.py
      network/f5/bigip_monitor_tcp.py
      network/f5/bigip_node.py
      network/f5/bigip_pool_member.py
      network/f5/bigip_pool.py
      network/f5/bigip_virtual_server.py
      network/nmcli.py
      network/openvswitch_bridge.py
      network/openvswitch_port.py
      notification/irc.py
      notification/jabber.py
      notification/mail.py
      notification/mqtt.py"
before_install:
  - git config user.name "ansible"
  - git config user.email "ansible@ansible.com"
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then git rebase $TRAVIS_BRANCH; fi;
install:
  - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
  - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
script:
  - python2.4 -m compileall -fq -x 'cloud/|monitoring/zabbix.*\.py|/dnf\.py|/layman\.py|/maven_artifact\.py|clustering/(consul.*|znode)\.py|notification/pushbullet\.py|database/influxdb/influxdb.*\.py|database/mssql/mssql_db\.py|/letsencrypt\.py|network/f5/bigip.*\.py|remote_management/ipmi/.*\.py|cloud/atomic/atomic_.*\.py' .
  - python2.6 -m compileall -fq .
  - python2.7 -m compileall -fq .
  - python3.4 -m compileall -fq . -x $(echo "$PY3_EXCLUDE_LIST"| tr ' ' '|')
  - python3.5 -m compileall -fq . -x $(echo "$PY3_EXCLUDE_LIST"| tr ' ' '|')
  - ansible-validate-modules .
  #- ./test-docs.sh extras
