dist: trusty
sudo: required
services:
  - docker
language: python
matrix:
  include:
    - env: TARGET=sanity TOXENV=py24
    - env: TARGET=sanity TOXENV=py26
      python: 2.6
    - env: TARGET=sanity TOXENV=py27
      python: 2.7
    - env: TARGET=sanity TOXENV=py34
      python: 3.4
    - env: TARGET=sanity TOXENV=py35
      python: 3.5
    - env: TARGET=centos6
    - env: TARGET=centos7 TARGET_OPTIONS="--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - env: TARGET=fedora23 TARGET_OPTIONS="--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - env: TARGET=fedora-rawhide TARGET_OPTIONS="--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - env: TARGET=ubuntu1204
    - env: TARGET=ubuntu1404
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
install:
  - pip install tox
script:
  - ./test/utils/run_tests.sh
after_success:
  - coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#ansible-notices"
    on_success: change
    on_failure: always
    skip_join: true
    nick: ansibletravis
