sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
      - python2.6
      - python3.5
before_install:
  - git config user.name "ansible"
  - git config user.email "ansible@ansible.com"
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then git rebase $TRAVIS_BRANCH; fi;
install:
  - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
  - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
script:
  - python2.4 -m compileall -fq -x 'cloud/' .
  - python2.4 -m compileall -fq cloud/amazon/_ec2_ami_search.py cloud/amazon/ec2_facts.py
  - python2.6 -m compileall -fq .
  - python2.7 -m compileall -fq .
  - python3.4 -m compileall -fq .
  - python3.5 -m compileall -fq .
  - ansible-validate-modules --exclude 'utilities/' .
    #- ansible-validate-modules --exclude 'cloud/amazon/ec2_lc\.py|cloud/amazon/ec2_scaling_policy\.py|cloud/amazon/ec2_scaling_policy\.py|cloud/amazon/ec2_asg\.py|cloud/azure/azure\.py|packaging/os/rhn_register\.py|network/openswitch/ops_template\.py|system/hostname\.py|utilities/' .
  #- ./test-docs.sh core
