[build-system]
requires = ["setuptools >= 66.1.0, <= 75.1.0"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
build-backend = "setuptools.build_meta"
