[build-system]
requires = ["setuptools >= 45.2.0, <= 72.1.0"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
build-backend = "setuptools.build_meta"
