---
- hosts: webservers
  vars:
  - jquery_directory: /var/www/html/javascript
  - person: 'Susie%20Smith'
  tasks:
  - name: Create directory for jQuery
    action: file dest={{jquery_directory}} state=directory mode=0755
  - name: Grab a bunch of jQuery stuff
    action: get_url url=http://code.jquery.com/{{item}}  dest={{jquery_directory}} mode=0444
    with_items:
    - jquery.min.js
    - mobile/latest/jquery.mobile.min.js
    - ui/jquery-ui-git.css
  #- name: Pass urlencoded name to CGI
  #  action: get_url url=http://example.com/name.cgi?name='{{person}}' dest=/tmp/test
