---
#
# NetScaler module example
#

- hosts: web-pool
  serial: 3
  vars:
  	nsc_host: nsc.example.com
  	nsc_user: admin
  	nsc_pass: nimda
  	# type of the netscaler object you want to manipulate
  	type: service
  	# netscaler object name
  	name: "{{facter_fqdn}}:8080"

  tasks:
  	- name: disable service in the lb
  	  action: netscaler nsc_host={{nsc_host}} user={{nsc_user}} password={{nsc_pass}} name={{name}} type={{type}} action=disable

  	- name: deploy new code
  	  action: shell yum upgrade -y

  	- name: enable in the lb
  	  action: netscaler nsc_host={{nsc_host}} user={{nsc_user}} password={{nsc_pass}} name={{name}} type={{type}} action=enable
