---

# this is the example of an included tasks file.  It contains a flat list of tasks
# they can notify other tasks, and have full access to variables from 'vars'
# or 'vars_files' directives.  Further, if ohai or facter were installed on
# the remote machines, variables from those tools can be accessed on the 'action'
# line or in templates.  Just prefix with 'facter_' or 'ohai_' before the particular
# variable.

# possible uses for a included yaml file might be to represent a 'class' of a system
# like defining what makes up a webserver, or you might have a common 'base.yml'
# (like this) that might be applied to all your systems as well.

- name: no selinux
  action: command /usr/sbin/setenforce 0

- name: no iptables
  action: service name=iptables state=stopped

- name: made up task just to show variables work here
  action: command /bin/echo release is $release
