- pattern: '*'
  tasks:
  - do:
    - configure template & module variables
    - setup
    - [ "a=2", "b=3", "c=4" ]
  - do:
    - template from local file template.j2 to remote location /srv/file.out
    - template
    - [ '/srv/template.j2', '/srv/file.out' ]
  - do:
    - update apache
    - command
    - [/usr/bin/yum, update, apache]
    onchange:
    - do:
      - restart apache
      - command
      - [/sbin/service, apache, restart]
    - do:
      - run bin false
      - command
      - [/bin/false]

