trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

schedules:
  - cron: 0 7 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - devel
        - stable-*

variables:
  - name: checkoutPath
    value: ansible
  - name: coverageBranches
    value: devel
  - name: pipelinesCoverage
    value: coverage
  - name: entryPoint
    value: test/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 500

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.8.0

pool: Standard

stages:
  - stage: Remote
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: RHEL 8.4b py36
              test: rhel/8.4b@3.6
            - name: RHEL 8.4b py38
              test: rhel/8.4b@3.8
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Incidental_Remote
    displayName: Incidental Remote
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: i/{0}
          targets:
            - name: RHEL 8.4b py36
              test: rhel/8.4b@3.6
            - name: RHEL 8.4b py38
              test: rhel/8.4b@3.8
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Remote
      - Incidental_Remote
    jobs:
      - template: templates/coverage.yml
